name: Tests

on:
  push:
  pull_request:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v5

      - name: Build
        run: make test-build

      - name: Test
        run: make test

      - name: Lint
        run: ./gradlew ktlintCheck detekt
